name: Build and Lint

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  lint:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - name: lint
        env:
          CI: true
        run: npm run lint
